.PHONY: all build test clean sync-work

all: sync-work provision-llama build test

sync-work:
	go work sync

provision-llama:
	bash scripts/provision_llama.sh

build:
	CGO_ENABLED=1 go build ./services/engine/...
	CGO_ENABLED=1 go build ./apps/proxy/...
	CGO_ENABLED=1 go build ./apps/sombra/...
	CGO_ENABLED=1 go build ./enterprise/engine-extensions/...

test:
	CGO_ENABLED=1 go test ./services/engine/...
	CGO_ENABLED=1 go test ./apps/proxy/...
	CGO_ENABLED=1 go test ./apps/sombra/...
	CGO_ENABLED=1 go test ./enterprise/engine-extensions/...

clean:
	go clean -cache
	rm -rf dist/
