.PHONY: all build test clean sync-work

all: sync-work build test

sync-work:
	go work sync

build:
	go build ./services/engine/...
	go build ./apps/proxy/...
	go build ./apps/sombra/...
	go build ./enterprise/engine-extensions/...

test:
	go test ./services/engine/...
	go test ./apps/proxy/...
	go test ./apps/sombra/...
	go test ./enterprise/engine-extensions/...

clean:
	go clean -cache
	rm -rf dist/
